ly:
  jwt:
    pubKeyPath: F:/hm/ssh/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  redis:
    cartKey: CART_PREFIX
server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.134
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 10 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 50 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}